version: "3.9"

services:
  api:
    build:
      context: .
      target: prod
    container_name: finwise_api
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: finwise_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finwise
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      retries: 10

  tests:
    build:
      context: .
      target: test
    container_name: finwise_tests
    depends_on:
      db_test:
        condition: service_healthy
    env_file: .env.test

  db_test:
    image: postgres:15
    container_name: finwise_db_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finwise_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      retries: 10
