services:
  # 1. Loki: The Log Database
  loki:
    image: grafana/loki:2.9.2
    container_name: finwise_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - finwise-network

  # 2. Promtail: The Log Shipper
  promtail:
    image: grafana/promtail:2.9.2
    container_name: finwise_promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./monitoring/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - finwise-network

  # 3. Grafana: The Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: finwise_grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - loki
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - finwise-network

volumes:
  grafana_data:

networks:
  finwise-network:
    external: true